### ISSUE TITLE
HBC update caused gem to stop working

### ISSUE THREAD

**Issue by adidalal** [buo/brew-cask-upgrade#5]
Seems to be looking for something that's missing from `vendor/homebrew-fork/global`

```ruby
 [.../homebrew-cask/Casks] > brew-cask-upgrade
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- exceptions (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/brew-cask-upgrade-1.0.1/lib/brew-cask-upgrade.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/brew-cask-upgrade-1.0.1/bin/brew-cask-upgrade:5:in `<top (required)>'
	from /usr/local/bin/brew-cask-upgrade:22:in `load'
	from /usr/local/bin/brew-cask-upgrade:22:in `<main>'
```

<details><summary>Output of `gem list`</summary>

```
*** LOCAL GEMS ***

bigdecimal (default: 1.2.8)
brew-cask-upgrade (1.0.1)
did_you_mean (1.0.0)
io-console (default: 0.4.5)
json (default: 1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (default: 2.0.17)
rake (10.4.2)
rdoc (default: 4.2.1)
test-unit (3.1.5)
```
</details>

<details><summary>Output of `ruby --version`</summary>

```
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```
</details>

-----

Likely related to either https://github.com/caskroom/homebrew-cask/pull/22574 or https://github.com/caskroom/homebrew-cask/pull/22464

**Comment by adidalal** [comment]
Looks to be a HBC issue, actually. I'll look into it.
