### ISSUE TITLE
/usr/local/Library/Homebrew/download_strategy.rb:6:in `<class:AbstractDownloadStrategy>': uninitialized constant AbstractDownloadStrategy::FileUtils (NameError)

### ISSUE THREAD

**Issue by giacgbj** [buo/brew-cask-upgrade#6]
It happened after the latest "brew update", without updating any package.

What could be?

```
brew-cask-upgrade 
/usr/local/Library/Homebrew/download_strategy.rb:6:in `<class:AbstractDownloadStrategy>': uninitialized constant AbstractDownloadStrategy::FileUtils (NameError)
	from /usr/local/Library/Homebrew/download_strategy.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/resource.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/brew-cask-upgrade-1.0.2/lib/brew-cask-upgrade.rb:6:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/brew-cask-upgrade-1.0.2/bin/brew-cask-upgrade:5:in `<top (required)>'
	from /usr/local/bin/brew-cask-upgrade:23:in `load'
	from /usr/local/bin/brew-cask-upgrade:23:in `<main>'

```

**Comment by giacgbj** [comment]
Now the error is

```
/usr/local/bin/brew-cask-upgrade:23:in `load': /Library/Ruby/Gems/2.0.0/gems/brew-cask-upgrade-2.0.0/bin/brew-cask-upgrade:3: syntax error, unexpected tIDENTIFIER, expecting end-of-input (SyntaxError)
	from /usr/local/bin/brew-cask-upgrade:23:in `<main>'
```

on Mac OS X El Capitan.

Let me know if you need any further information.

**Comment by adidalal** [comment]
Uninstall `brew-cask-upgrade` gem.

To install the latest version, use `brew tap buo/cask-upgrade`. To update: `brew update; brew cu`

**Comment by buo** [comment]
@giacgbj: It seems like you are using the old version of `brew-cask-upgrade` executable. You may use `brew-cask-upgrade` gem, but please update the `/usr/local/bin/brew-cask-upgrade` to the latest version.

**Comment by buo** [comment]
As @adidalal said, it is recommended to use brew tap instead of Ruby gem. `brew-cask-upgrade` executable still remains for the backward compatibility.
